### ISSUE TITLE
Contact Card feedback

### ISSUE THREAD

**Issue by anexact** [usergroupcoop/cognicity_msf-design#1]
Request for contact cards to open in new window/new tab.
Bug -  contact cards 'submit' button doesn't appear to work yet, or doesn't time out.
Following successful submission, can use receive a "Submitted" screen?
MB - standing by on WA / email if you want to ping any questions.

**Comment by matthewberryman** [comment]
The submit button was working and completed as part of design, and took you to a submitted screen, but I broke the javascript in updating all the contacts fields. Opened https://github.com/usergroupcoop/msf-reach/issues/50 as a bug issue.

Opening in new window/tab is something I will work on more generally in https://github.com/usergroupcoop/msf-reach/issues/49
